default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  host: <%= ENV['DB_HOST'] %>
  port: 5432
  pool: 5

development:
  <<: *default
  database: shorten_url_development

test:
  <<: *default
  database: shorten_url_test
